FROM gemstone-base:latest

ARG BARCH=x86_64

ARG BBRANCH=master

ENV BUILD_ARCH=$BARCH

ENV GIT_BRANCH=$BBRANCH

ENV PACKAGE_ALL=yes

WORKDIR /root

RUN git clone https://github.com/project-gemstone/scratchpkg.git && cd scratchpkg && make install

RUN git clone --branch $GIT_BRANCH https://github.com/project-gemstone/quarry.git

WORKDIR /root/quarry

RUN chmod +x utils/* && cp utils/* /usr/local/bin

ENTRYPOINT ["/bin/bash", "-c"]
